openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: ''
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Articles
    description: Articles list
paths:
  /api/articles:
    get:
      tags:
        - Articles
      summary: Search all articles
      operationId: searchArticle
      description: Search all articles
      responses:
        '200':
          description: Search all articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          description: bad input parameter
    post:
      tags:
        - Articles
      summary: Add new article
      operationId: addArticle
      description: Add new article
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
              properties:
                title:
                  type: string
                  example: Cat crusaders
                description:
                  type: string
                  example: Intergalactic cats crusade against martians
        description: Article to add
      responses:
        '201':
          description: Articles list with a new article
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          description: 'invalid input, object invalid'
    delete:
      tags:
        - Articles
      summary: Delete all articles
      operationId: deleteArticle
      description: Delete all articles
      responses:
        '200':
          description: Empty array, all articles deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  example: 
        '400':
          description: bad input parameter
  /api/articles/{id}:
    get:
      tags:
        - Articles
      summary: Search article by id
      operationId: searchArticleByID
      description: Search article by id
      parameters:
       - name: id
         in: path
         description: ID of article to return
         required: true
         schema:
            type: integer
            format: int64
      description: search article by ID
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Article'
        '400':
          description: Article not found
    patch:
      tags:
        - Articles
      summary: Update article by id
      operationId: updateArticleByID
      description: Update article by id
      parameters:
       - name: id
         in: path
         description: ID of article to update
         required: true
         schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - description
              properties:
                description:
                  type: string
                  example: Intergalactic cats crusade against martians
        description: Article to add
      responses:
        '200':
          description: Articles list with an updated article
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          description: Article not found
    delete:
      tags:
        - Articles
      summary: Delete article by id
      operationId: deleteArticle
      description: Delete article by id
      parameters:
       - name: id
         in: path
         description: ID of article to delete
         required: true
         schema:
            type: integer
            format: int64
      description: Delete article by ID
      responses:
        '201':
          description: Articles list without a deleted article
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          description: Article not found

definitions:
  Article:
    type: object
    required:
      - description
    properties:
      description:
        type: string
components:
  schemas:
    Article:
      type: object
      required:
        - id
        - title
        - description
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Space Cat
        description:
          type: string
          example: Cat has landed on the Moon
    Articles:
      type: array
      items: 
        $ref: '#/components/schemas/Article'